address: https://test-stand.gb.ru/gateway/login 
username: Oleggov666
password: 256ec8af00
address2: https://test-stand.gb.ru/api/posts
titlee: ABOUT SWEET BREAD
descriptionn: DESCRIPTION OF SWEET BREAD
contentt: A LOT OF SWEET BREAD